import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Container, Spinner } from "@chakra-ui/react";
import Navbar from "../components/Navbar";
import { useState, useEffect } from "react";
import Axios from "axios";
import Card from "../components/Card";
import CardGroup from "../components/CardGroup";
export default function Home() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState([]);
  const [cardData, setCardData] = useState([]);

  useEffect(() => {
    setLoading(true);
    Axios.get("https://api.publicapis.org/categories")
      .then((res) => {
        setData(res.data.categories);
        // console.log(res.data.categories);
        // setLoading(false);
      })
      .catch((err) => {
        console.log("Error occured!");
        return;
      });
    Axios.get("https://api.publicapis.org/entries")
      .then((res) => {
        setCardData(res.data.entries);
      })
      .catch((err) => {
        console.log("Error occured!");
      });
    setLoading(false);
  }, []);

  if (loading) {
    return (
      <div className="ml-72">
        Loading page...
        <Spinner
          className="h-5 w-6"
          thickness="4px"
          speed="0.65s"
          emptyColor="gray.200"
          color="blue.500"
        />
      </div>
    );
  } else {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Navbar data={data} />
          <br />
          {/* <Card /> */}
          <CardGroup data={cardData} />
        </main>
      </div>
    );
  }
}
