import Head from "next/head";
import {
  Container,
  InputGroup,
  InputRightElement,
  Input,
  IconButton,
  Spinner,
} from "@chakra-ui/react";
import Dropdown from "../components/Dropdown";
import { SearchIcon, Search2Icon } from "@chakra-ui/icons";
import { useState, useEffect } from "react";
import Axios from "axios";
import CardGroup from "../components/CardGroup";
export default function Home() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState([]);
  const [cardData, setCardData] = useState([]);
  const [tempData, setTempData] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    let term = searchTerm.replace("+", " ");
    let match = [];
    cardData.map((value, index) => {
      if (value.Description.includes(term)) {
        match.push(value);
      }
    });
    setTempData(match);
  }, [searchTerm]);
  useEffect(() => {
    setLoading(true);
    Axios.get("https://api.publicapis.org/categories")
      .then((res) => {
        setData(res.data.categories);
      })
      .catch((err) => {
        console.log("Error occured!");
        return;
      });
    Axios.get("https://api.publicapis.org/entries")
      .then((res) => {
        setCardData(res.data.entries);
        setTempData(res.data.entries);
      })
      .catch((err) => {
        console.log("Error occured!");
      });
    setLoading(false);
  }, []);

  if (loading) {
    return (
      <div className="ml-72">
        Loading page...
        <Spinner
          className="h-5 w-6"
          thickness="4px"
          speed="0.65s"
          emptyColor="gray.200"
          color="blue.500"
        />
      </div>
    );
  } else {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Container className="flex justify-around flex-row flex-wrap mt-3 shadow-md ">
            <nav>
              <h1 class="font-extrabold text-transparent text-xl bg-clip-text bg-gradient-to-r from-green to-blue text-clip text-blue">
                Home
              </h1>
            </nav>
            <nav>
              <Container color="white" className="mb-3">
                <InputGroup>
                  <Input
                    className="p-2 w-5xl bg-gray-light "
                    type="text"
                    placeholder="Search Here"
                    color="black"
                    onChange={(e) => {
                      setSearchTerm(e.target.value);
                      // setInputQuery(e.target.value);
                    }}
                  />
                  <InputRightElement>
                    <IconButton
                      className="h-10  bg-blue  w-10 "
                      size="md"
                      colorScheme="blackAlpha"
                      aria-label="Get request"
                      icon={<Search2Icon />}
                    />
                  </InputRightElement>
                </InputGroup>
              </Container>
            </nav>
            <nav>
              <Dropdown data={data} />
            </nav>
          </Container>
          <br />
          {tempData.length == 0 ? (
            <div className="ml-96 text-lg font-bold  mt-60">
              Sorry nothing found!
            </div>
          ) : (
            <CardGroup data={tempData} />
          )}
        </main>
      </div>
    );
  }
}
